##### Numpy (Numerical Python)
- ndarray n-차원의 배열 
- 배열에 대한 동작은 파이썬의 리스트 보다 두자릿수 이상 빠르다. 
- 450 개의 파이썬 라이브러리가 Numpy에 의존하고 있다. 

In [4]:
import numpy as np 

numbers = np.array([2, 3, 4, 7, 11])
print(type(numbers))
print(numbers)

numbers = np.array([[1, 2, 3], [4, 5, 6]])
print(numbers)
print("="*40)
integers = np.array([[1, 2, 3], [4, 5, 6]])
print(integers)
print(integers.dtype)
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
print(floats)
print(floats.dtype)

print(integers.ndim)
print(integers.shape)
print(floats.shape)

("\n")
print(integers.size)

<class 'numpy.ndarray'>
[ 2  3  4  7 11]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
int32
[0.  0.1 0.2 0.3 0.4]
float64
2
(2, 3)
(5,)
6


In [15]:
np_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for rows in np_1:
    for col in rows:
        print(col, end= " ")
    print()
np_2 = np.array([[x for x in range(1, 4)], [y for y in range(4, 7)]])

for i in np_2.flat:
    print(i, end=" ")

1 2 3 
4 5 6 
7 8 9 
1 2 3 4 5 6 

In [19]:
np1 = np.zeros(5)
for i in np1.flat:
    print(i)
    
np2 = np.ones((2, 5), dtype=int)
for rows in np2:
    for col in rows:
        print(col, end=" ")
    print() 
    
np3 = np.full((3, 4), 22)

for rows in np3:
    for col in rows:
        print(col, end=" ")
    print()

np1 = np.arange(5)
print(np1)
np2 = np.arange(5, 10)
print(np2)
np3 = np.arange(10, 1, -1)
print(np3)

0.0
0.0
0.0
0.0
0.0
1 1 1 1 1 
1 1 1 1 1 
22 22 22 22 
22 22 22 22 
22 22 22 22 


In [7]:
import numpy as np 
np_1 = np.linspace(0.0, 1.0, num=5)
print(np_1)
np_2 = np.arange(1, 21)
np_2 = np.arange(1, 21).reshape(4, 5)
print(np_2)


[0.   0.25 0.5  0.75 1.  ]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [25]:
import numpy as np 

numbers1 = np.arange(1, 6)
print(numbers1)
print(numbers1 * 2)
print(numbers1 ** 3)
print("numbers1 :", numbers1)
# numbers1 += 10
# print("numbers1 :", numbers1)


numbers2 = np.linspace(1.1, 5.5, 5)
print(numbers1 * numbers2) 

numbers3 = np.arange(11, 16, 1)
print(numbers3)

print(numbers3 >= 13)

numbers4 = np.linspace(1.1, 5.5, 5)
print(numbers4)
print(numbers3 * numbers4)


[1 2 3 4 5]
[ 2  4  6  8 10]
[  1   8  27  64 125]
numbers1 : [1 2 3 4 5]
[ 1.1  4.4  9.9 17.6 27.5]
[11 12 13 14 15]
[False False  True  True  True]
[1.1 2.2 3.3 4.4 5.5]
[12.1 26.4 42.9 61.6 82.5]


In [29]:
import numpy as np 

grades = np.array([[87, 96, 70],
                   [100, 87, 90], 
                   [94, 77, 90], 
                   [100, 81, 82]])

print(grades.sum())
print(grades.min())
print(grades.max())
print(grades.mean())
print(grades.std())
print(grades.var())

print(grades.sum(axis=0))

1073
70
100
89.41666666666667
9.810354507129473
96.24305555555556
[400 341 332]


In [37]:
import numpy as np 

lst = [x**2 for x in range(1, 7)]
numbers1 = np.array(lst)
print(numbers1)
np_1 = np.sqrt(numbers1)
print(np_1)

numbers2 = np.arange(1, 7) * 10 
print(numbers2)
print(np.add(numbers1, numbers2))
print(np.multiply(numbers2, 5))
numbers3 = numbers2.reshape(2, 3)

print(numbers3)


[ 1  4  9 16 25 36]
[1. 2. 3. 4. 5. 6.]
[10 20 30 40 50 60]
[11 24 39 56 75 96]
[ 50 100 150 200 250 300]
[[10 20 30]
 [40 50 60]]
